import { STUDENT_DOCUMENT_V1, type StudentDocumentMediaAsset, type StudentDocumentV1 } from './studentDocument.types';

const smoke = (subject: string, detail: string) =>
  `SMOKE / DEMO / NON EDITORIAL CONTENT. ${subject} se presenta aquí como material ficticio para comprobar la lectura continua de un documento largo. ${detail} La descripción no pretende fijar hechos, fechas ni interpretaciones; combina nombres plausibles con Lorem Ipsum editorial para probar anchura, interlineado, selección de texto y pausas visuales. Cada frase existe únicamente para dar densidad realista al prototipo y para mostrar cómo una explicación enciclopédica puede avanzar con claridad de un párrafo a otro.`;

export const smokeStudentMedia: Record<string, StudentDocumentMediaAsset> = {
  'student-geo': { id: 'student-geo', url: '/destinations/cuenca/shared/landscape/serrania.png', alt: 'Barranco boscoso y paredes calizas de la Serranía', credit: 'Archivo de smoke de Trawel', source: 'Fixture local Cuenca', license: 'DEMO ONLY' },
  'student-history': { id: 'student-history', url: '/destinations/cuenca/shared/detail/llamador-historico.png', alt: 'Detalle arquitectónico histórico de Cuenca', credit: 'Archivo de smoke de Trawel', source: 'Fixture local Cuenca', license: 'DEMO ONLY' },
  'student-heritage': { id: 'student-heritage', url: '/destinations/cuenca/shared/hero/casas-colgadas-atardecer.png', alt: 'Casas Colgadas de Cuenca al atardecer', credit: 'Archivo de smoke de Trawel', source: 'Fixture local Cuenca', license: 'DEMO ONLY' },
  'student-nature': { id: 'student-nature', url: '/destinations/cuenca/shared/wildcard/ciudad-encantada.png', alt: 'Formaciones rocosas de la Ciudad Encantada', credit: 'Archivo de smoke de Trawel', source: 'Fixture local Cuenca', license: 'DEMO ONLY' },
  'student-food': { id: 'student-food', url: '/destinations/cuenca/shared/food/gastronomia-mirador.png', alt: 'Mesa gastronómica con paisaje urbano', credit: 'Archivo de smoke de Trawel', source: 'Fixture local Cuenca', license: 'DEMO ONLY' },
};

export const smokeCanonicalStudentDocument: StudentDocumentV1 = {
  version: STUDENT_DOCUMENT_V1,
  headline: 'Cuenca: lectura territorial, histórica y cultural',
  lead: [
    smoke('Esta entrada de Cuenca', 'Su propósito es validar la composición canónica que en producción llegará ordenada desde Investighost.'),
    smoke('El recorrido propone una ciudad imaginada por capas', 'Territorio, memoria, patrimonio y vida cotidiana se encadenan sin que el frontend altere la secuencia entregada.'),
    smoke('Los datos, referencias y cronologías son deliberadamente ficticios', 'La maqueta conserva su forma de enciclopedia digital para permitir una revisión humana de ritmo y jerarquía.'),
    smoke('El documento también ensaya el equilibrio entre bloques compactos y desarrollo extenso', 'Las imágenes aparecen en posiciones explícitas y sus pies no se separan del contexto editorial.'),
  ],
  blocks: [
    { type: 'heading', level: 2, id: 'geografia-territorio', text: 'Geografía y territorio' },
    { type: 'paragraph', text: smoke('El territorio', 'Una primera mirada ficticia describe laderas, cursos de agua y umbrales construidos que ayudan a situar la lectura.') },
    { type: 'paragraph', text: smoke('La relación entre relieve y asentamiento', 'El texto prolongado ensaya transiciones suaves entre una observación espacial y la siguiente capa histórica.') },
    { type: 'paragraph', text: smoke('La escala del paisaje', 'Las referencias son inventadas y solo buscan demostrar cómo conviven orientación general, detalle y vocabulario preciso.') },
    { type: 'figure', assetId: 'student-geo', placement: 'WIDE', alt: 'Barranco boscoso y paredes calizas de la Serranía', caption: 'SMOKE / DEMO. Paisaje territorial ficticio para comprobar una figura WIDE y su pie contextual.' },
    { type: 'paragraph', text: smoke('El paisaje visible', 'Después de la imagen, el documento retoma la columna de lectura sin convertir la fotografía en un corte de experiencia.') },
    { type: 'heading', level: 2, id: 'historia', text: 'Historia' },
    { type: 'paragraph', text: smoke('La historia de esta maqueta', 'El hilo narrativo no afirma una verdad documental: prueba el paso desde una apertura amplia hasta episodios más concretos.') },
    { type: 'heading', level: 3, id: 'origenes', text: 'Orígenes' },
    { type: 'paragraph', text: smoke('Los orígenes', 'La prosa de muestra contiene repeticiones deliberadas para probar la continuidad de párrafos de longitud comparable.') },
    { type: 'paragraph', text: smoke('Las primeras ocupaciones', 'Los nombres y relaciones se mantienen neutros; el contrato real recibirá la investigación aprobada sin reformulación en Trawel.') },
    { type: 'figure', assetId: 'student-history', placement: 'INLINE', alt: 'Detalle arquitectónico histórico de Cuenca', caption: 'SMOKE / DEMO. Detalle histórico ficticio insertado entre los subcapítulos de historia.' },
    { type: 'heading', level: 3, id: 'periodo-medieval', text: 'Periodo medieval' },
    { type: 'paragraph', text: smoke('El periodo medieval', 'Este pasaje simula una explicación de cambios urbanos, redes de intercambio y construcción de referencias compartidas.') },
    { type: 'paragraph', text: smoke('Las continuidades locales', 'El diseño debe dejar que la voz editorial respire y conservar esta posición exacta antes del siguiente periodo.') },
    { type: 'heading', level: 3, id: 'edad-moderna', text: 'Edad moderna' },
    { type: 'paragraph', text: smoke('La edad moderna', 'El documento prolonga la lectura con una falsa secuencia de ajustes institucionales, materiales y simbólicos.') },
    { type: 'paragraph', text: smoke('La transformación de los usos', 'La intención visual es verificar jerarquía H3, separación de bloques y confort tipográfico durante varios minutos.') },
    { type: 'timeline', title: 'Cronología de smoke', items: [
      { label: 'Siglo XII', text: 'Primer hito ficticio de ocupación y paso territorial.' }, { label: '1240', text: 'Referencia de smoke para una reorganización imaginada.' }, { label: 'Siglo XIV', text: 'Construcción simbólica usada solo como prueba visual.' }, { label: '1492', text: 'Cambio de época ficticio en la cronología.' }, { label: 'Siglo XVI', text: 'Nueva capa urbana de demostración.' }, { label: 'Década de 1760', text: 'Reforma inexistente para probar labels no numéricos.' }, { label: '1924', text: 'Registro moderno ficticio.' }, { label: 'Década de 1970', text: 'Relectura patrimonial de smoke.' }, { label: 'Actualidad', text: 'Cierre de la línea de tiempo de demostración.' },
    ] },
    { type: 'heading', level: 2, id: 'patrimonio-arquitectura', text: 'Patrimonio y arquitectura' },
    { type: 'paragraph', text: smoke('El patrimonio', 'Una explicación ficticia pone en relación materia, escala urbana y memoria compartida sin reclamar exactitud factual.') },
    { type: 'paragraph', text: smoke('La arquitectura', 'Los párrafos prueban que la maqueta puede concentrar información sin reducir el documento a tarjetas o paneles.') },
    { type: 'figure', assetId: 'student-heritage', placement: 'WIDE', alt: 'Casas Colgadas de Cuenca al atardecer', caption: 'SMOKE / DEMO. Figura panorámica de patrimonio con caption editorial específico.' },
    { type: 'paragraph', text: smoke('La conservación imaginada', 'El retorno al texto después de una figura ancha permite revisar el ritmo entre observación visual y explicación.') },
    { type: 'list', style: 'unordered', items: ['Elemento ficticio de lectura urbana.', 'Material de smoke para probar listas semánticas.', 'Rastro arquitectónico sin valor documental.', 'Detalle visual pensado para la revisión de espaciado.'] },
    { type: 'heading', level: 2, id: 'arte-cultura', text: 'Arte y cultura' },
    { type: 'paragraph', text: smoke('El arte y la cultura', 'Esta sección despliega vocabulario de muestra para comprobar una lectura que alterna argumento, definición y figura.') },
    { type: 'paragraph', text: smoke('Las prácticas culturales', 'El contenido es inventado, pero su extensión ayuda a revisar los márgenes y la medida de la columna.') },
    { type: 'callout', tone: 'DEFINITION', title: 'Definición de smoke', text: 'Una definición ficticia y compacta para comprobar el tratamiento visual estable de un concepto clave, sin colores arbitrarios ni componentes de dashboard.' },
    { type: 'paragraph', text: smoke('Las mediaciones', 'Este bloque retoma el hilo tras el destacado y conserva la estructura fijada por el productor editorial.') },
    { type: 'figure', assetId: 'student-history', placement: 'INLINE', alt: 'Detalle arquitectónico histórico de Cuenca', caption: 'SMOKE / DEMO. Figura inline para probar cercanía entre lectura, imagen y pie.' },
    { type: 'heading', level: 2, id: 'sociedad-tradiciones', text: 'Sociedad y tradiciones' },
    { type: 'paragraph', text: smoke('La sociedad', 'La maqueta presenta una comunidad abstracta y no representa grupos reales ni prácticas reales.') },
    { type: 'paragraph', text: smoke('Las tradiciones', 'El objetivo es observar el color del cuerpo de texto y la respiración entre párrafos sin overlays.') },
    { type: 'paragraph', text: smoke('Los ritmos cotidianos', 'Una tercera unidad textual da continuidad antes de los datos destacados y permite revisar el salto de componente.') },
    { type: 'key_facts', title: 'Datos rápidos de smoke', items: [{ label: 'Estado', value: 'Demostración no editorial' }, { label: 'Lectura', value: 'Documento ordenado' }, { label: 'Media', value: 'Assets locales de fixture' }, { label: 'Autoridad', value: 'Investighost en producción' }] },
    { type: 'heading', level: 2, id: 'lengua-identidad-toponimia', text: 'Lengua, identidad y toponimia' },
    { type: 'paragraph', text: smoke('La lengua y la identidad', 'Este apartado es ficticio y permite comprobar cómo se comportan encabezados extensos en escritorio y móvil.') },
    { type: 'paragraph', text: smoke('La toponimia', 'Las palabras funcionan como relleno estructurado y nunca como fuente de información sobre el destino real.') },
    { type: 'heading', level: 2, id: 'naturaleza-medio-ambiente', text: 'Naturaleza y medio ambiente' },
    { type: 'paragraph', text: smoke('La naturaleza', 'El relato ensaya relaciones ambientales sin convertir esta maqueta en una recomendación de viaje o una guía factual.') },
    { type: 'paragraph', text: smoke('El medio ambiente', 'La longitud permite valorar la lectura de un bloque sustantivo antes de una nueva pausa de imagen.') },
    { type: 'figure', assetId: 'student-nature', placement: 'WIDE', alt: 'Formaciones rocosas de la Ciudad Encantada', caption: 'SMOKE / DEMO. Paisaje natural ficticio para validar una segunda figura WIDE.' },
    { type: 'paragraph', text: smoke('La gestión imaginada del paisaje', 'La prosa vuelve a la medida normal de columna, confirmando la continuidad tras una imagen ancha.') },
    { type: 'heading', level: 2, id: 'economia-evolucion-social', text: 'Economía y evolución social' },
    { type: 'paragraph', text: smoke('La economía', 'Las conexiones y periodos citados son enteramente inventados y no deben ser usados fuera de esta revisión visual.') },
    { type: 'paragraph', text: smoke('La evolución social', 'El bloque mantiene densidad suficiente para ensayar lectura larga sin usar Markdown opaco ni recomposición de cliente.') },
    { type: 'heading', level: 2, id: 'gastronomia', text: 'Gastronomía y cultura alimentaria' },
    { type: 'paragraph', text: smoke('La gastronomía', 'La página utiliza este asunto solo como estructura editorial y no como recomendación ni descripción verificable.') },
    { type: 'paragraph', text: smoke('La cultura alimentaria', 'Las frases se organizan para probar la relación de la imagen inline con una sección de cuerpo completo.') },
    { type: 'figure', assetId: 'student-food', placement: 'INLINE', alt: 'Mesa gastronómica con paisaje urbano', caption: 'SMOKE / DEMO. Imagen inline de gastronomía, con atribución del asset por debajo.' },
    { type: 'list', style: 'ordered', items: ['Observar la relación entre texto y pie de foto.', 'Comprobar el sangrado de una lista ordenada.', 'Revisar la continuidad de foco por teclado.', 'Validar que todo el texto se puede seleccionar.'] },
    { type: 'heading', level: 2, id: 'conceptos-clave', text: 'Conceptos clave' },
    { type: 'key_facts', title: 'Glosario de smoke', items: [{ label: 'Contrato', value: 'StudentDocumentV1' }, { label: 'Orden', value: 'Autoritativo' }, { label: 'Composición', value: 'Investighost' }, { label: 'Render', value: 'Trawel' }, { label: 'Figura inline', value: 'Anchura de lectura' }, { label: 'Figura wide', value: 'Más ancha, no full bleed' }, { label: 'Caption', value: 'Contexto editorial' }, { label: 'Alt', value: 'Accesible y técnico' }, { label: 'Estado', value: 'Smoke local' }] },
    { type: 'heading', level: 2, id: 'sintesis', text: 'Síntesis' },
    { type: 'paragraph', text: smoke('La síntesis', 'La estructura completa demuestra que un documento largo puede mantener una jerarquía estable y una navegación útil.') },
    { type: 'paragraph', text: smoke('El cierre', 'La revisión humana debe valorar la página como contrato de lectura, no como contenido factual ni propuesta de investigación.') },
    { type: 'references', items: [
      { label: 'SMOKE-01', title: 'Atlas imaginario de la ciudad de prueba', source: 'Archivo ficticio de demostración', url: 'https://example.com/smoke-atlas' }, { label: 'SMOKE-02', title: 'Cuaderno de territorio no editorial', source: 'Colección Lorem', url: 'https://example.com/smoke-territorio' }, { label: 'SMOKE-03', title: 'Cronología inventada para maqueta', source: 'Demo editorial', url: 'https://example.com/smoke-cronologia' }, { label: 'SMOKE-04', title: 'Notas ficticias sobre patrimonio', source: 'Biblioteca de prueba', url: 'https://example.com/smoke-patrimonio' }, { label: 'SMOKE-05', title: 'Glosario de visualización Student', source: 'Fixture local', url: 'https://example.com/smoke-glosario' }, { label: 'SMOKE-06', title: 'Referencias de control de ritmo', source: 'Documento no editorial', url: 'https://example.com/smoke-ritmo' },
    ] },
  ],
};
